name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/typescript-action@releases/v1
      with:
        repo-token: ${{ secrets.TOKEN }}
        teams: "test"
