name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/typescript-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        persons: "rowi1de"
        teams: "no-team"
